[package]
name = "hcxmaptool"
version = "0.1.0"
edition = "2024"
authors = ["UwUDev"]

[dependencies]
chrono = "0.4.42"
nmea = "0.7.0"
pcap-file = "2.0.0"
radiotap = "1.3.0"
log = "0.4"
pretty_env_logger = "0.5"
clap = "4.5.40"
clap-help = "1.4.0"
once_cell = "1.19"
